"""Main system daemon: continuously listens for the "Hey Chatter" wake word
and, once heard, captures a command, requests synthesized speech, and plays
it back.

The daemon calls the audio-hardware MCP server's `record_audio`/`play_audio`
tools rather than touching `sounddevice` directly. Those tools are defined as
plain (sync) functions in mcp_server/audio_hardware_mcp.py, and FastMCP runs
sync tools in a worker thread by default (`run_in_thread=True`), so the
blocking `sounddevice` calls never stall this daemon's event loop -- other
async work (the HTTP call to /generate-speech, loop bookkeeping) keeps running
while a recording is in progress.
"""

import asyncio
import logging
import wave
from pathlib import Path
from typing import Optional

import httpx
import numpy as np
from fastmcp import Client

from app.main import OUTPUT_AUDIO_PATH as GENERATED_SPEECH_PATH
from mcp_server import audio_hardware_mcp

logger = logging.getLogger(__name__)

# -- Wake word detection constants --
# Kept in sync with train_wakeword.py's model shape/threshold, duplicated
# here (rather than imported) so this module stays importable even when
# tensorflow/microwakeword aren't installed -- tensorflow is only imported
# lazily, inside _load_interpreter, the first time real detection runs.
SAMPLE_RATE_HZ = 16000
FEATURE_COUNT = 40
SPECTROGRAM_LENGTH = 49
DETECTION_THRESHOLD = 0.9
WAKEWORD_TFLITE_PATH = Path("models/hey_chatter.tflite")

# -- Daemon loop constants --
LISTEN_CHUNK_DURATION_S = 2.0
COMMAND_CAPTURE_DURATION_S = 5.0
AUDIO_CHUNK_DIR = Path("audio_data")
LISTEN_CHUNK_PATH = AUDIO_CHUNK_DIR / "listen_chunk.wav"
COMMAND_CAPTURE_PATH = AUDIO_CHUNK_DIR / "command_capture.wav"
GENERATE_SPEECH_URL = "http://localhost:8000/generate-speech"
HARDCODED_RESPONSE_TEXT = "Hello! I heard you say the wake word."


def _load_interpreter():
    """Load the trained wake word .tflite model. Deferred import: tensorflow
    is only required once the daemon actually starts detecting for real.
    """
    import tensorflow as tf

    interpreter = tf.lite.Interpreter(model_path=str(WAKEWORD_TFLITE_PATH))
    interpreter.allocate_tensors()
    return interpreter


def _extract_features(wav_path: Path) -> np.ndarray:
    """Compute a log-magnitude spectrogram from a WAV clip, shaped to match
    the model's expected (SPECTROGRAM_LENGTH, FEATURE_COUNT) input.

    This is a lightweight, self-contained stand-in for wiring the detection
    loop end-to-end. For real accuracy, swap this for microWakeWord's own
    audio frontend (the same feature pipeline used during training) -- the
    trained model expects features generated by that exact pipeline.
    """
    with wave.open(str(wav_path), "rb") as wav_file:
        sample_rate = wav_file.getframerate()
        raw = wav_file.readframes(wav_file.getnframes())

    samples = np.frombuffer(raw, dtype="int16").astype("float32") / 32768.0

    frame_length = max(int(sample_rate * 0.030), 1)  # 30ms analysis window
    frame_step = max(int(sample_rate * 0.020), 1)  # 20ms stride

    features = np.zeros((SPECTROGRAM_LENGTH, FEATURE_COUNT), dtype="float32")
    bin_edges = np.linspace(0, frame_length // 2 + 1, FEATURE_COUNT + 1).astype(int)

    for frame_idx in range(SPECTROGRAM_LENGTH):
        start = frame_idx * frame_step
        frame = samples[start : start + frame_length]
        if frame.size == 0:
            break

        spectrum = np.abs(np.fft.rfft(frame, n=frame_length))
        for bin_idx in range(FEATURE_COUNT):
            lo, hi = bin_edges[bin_idx], max(bin_edges[bin_idx + 1], bin_edges[bin_idx] + 1)
            features[frame_idx, bin_idx] = np.log(np.mean(spectrum[lo:hi]) + 1e-6)

    return features


def detect_wake_word(interpreter, wav_path: Path, threshold: float = DETECTION_THRESHOLD) -> bool:
    """Run a recorded chunk through the wake word model and return whether
    its score clears the detection threshold.
    """
    features = _extract_features(wav_path)
    batch = np.expand_dims(features, axis=0)

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    interpreter.set_tensor(input_details[0]["index"], batch.astype(input_details[0]["dtype"]))
    interpreter.invoke()
    score = float(interpreter.get_tensor(output_details[0]["index"])[0][0])

    return score >= threshold


async def record_via_mcp(client: Client, duration: float, output_path: Path) -> Path:
    """Call the audio-hardware MCP server's record_audio tool."""
    result = await client.call_tool(
        "record_audio", {"duration": duration, "output_path": str(output_path)}
    )
    return Path(result.data)


async def play_via_mcp(client: Client, file_path: Path) -> str:
    """Call the audio-hardware MCP server's play_audio tool."""
    result = await client.call_tool("play_audio", {"file_path": str(file_path)})
    return result.data


async def request_generated_speech(text: str, url: str = GENERATE_SPEECH_URL) -> dict:
    """POST hardcoded text to the /generate-speech endpoint and return its JSON response."""
    async with httpx.AsyncClient() as http_client:
        response = await http_client.post(url, json={"text": text}, timeout=30.0)
        response.raise_for_status()
        return response.json()


async def run_agent_loop(
    interpreter=None,
    stop_event: Optional[asyncio.Event] = None,
    max_iterations: Optional[int] = None,
) -> None:
    """Continuously listen for "Hey Chatter" and respond when it's heard.

    Each cycle: record a 2s chunk, run it through the wake word model. If
    detected, record 5 more seconds, send a hardcoded response to
    /generate-speech, then play the synthesized result back.

    stop_event/max_iterations bound an otherwise-infinite loop for tests and
    graceful shutdowns; leave both unset for real continuous operation.
    """
    if interpreter is None:
        interpreter = _load_interpreter()

    AUDIO_CHUNK_DIR.mkdir(parents=True, exist_ok=True)

    iteration = 0
    async with Client(audio_hardware_mcp.mcp) as audio_client:
        while stop_event is None or not stop_event.is_set():
            if max_iterations is not None and iteration >= max_iterations:
                break
            iteration += 1

            try:
                await record_via_mcp(audio_client, LISTEN_CHUNK_DURATION_S, LISTEN_CHUNK_PATH)

                if detect_wake_word(interpreter, LISTEN_CHUNK_PATH):
                    logger.info("Wake word detected, capturing command")
                    await record_via_mcp(
                        audio_client, COMMAND_CAPTURE_DURATION_S, COMMAND_CAPTURE_PATH
                    )
                    await request_generated_speech(HARDCODED_RESPONSE_TEXT)
                    await play_via_mcp(audio_client, GENERATED_SPEECH_PATH)
            except Exception:
                logger.exception("Error during agent loop cycle; continuing")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(run_agent_loop())
